name: Send Lotto Numbers

on:
  schedule:
    # Tuesday and Friday at 08:00 UTC (Berlin/Zagreb: 10:00 CEST summer / 09:00 CET winter)
    - cron: "0 8 * * 2,5"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          DAD_NUMBER: ${{ secrets.DAD_NUMBER }}
          # Optional custom sender if your sandbox number differs (must include whatsapp: prefix)
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
        run: python lototata.py
