name: Send Lotto Numbers

on:
  schedule:
    # Tuesday and Friday at 08:00 UTC (Berlin: 10:00 CEST summer / 09:00 CET winter)
    - cron: "0 8 * * 2,5"
  workflow_dispatch: {}

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TWILIO_ACCOUNT_SID: ${{ AC8791f70edd64db6e26ac016681d07335 }}
          TWILIO_AUTH_TOKEN: ${{ 1780aa886302c3397d7076f8689f297a }}
          DAD_NUMBER: ${{ +385998167000 }}
          Optional custom sender if your sandbox number differs (must include whatsapp: prefix)
          TWILIO_WHATSAPP_FROM: ${{ +14155238886 }}
        run: python lototata.py
